name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nushell
        uses: hustcer/setup-nu@v3
        with:
          version: 'latest'

      - name: Install rip
        run: cargo install rm-improved

      - name: Install Carapace
        run: go install github.com/rsteube/carapace-bin@latest

      - name: Run tests
        run: nu test_rm.nu
